name: coverage
on: push

jobs:
  coverage:
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true # optional (default = false)